flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- annihilator-0.1.0.0
- hspec-2.4.4
- hspec-core-2.4.4
- hspec-discover-2.4.4
- printcess-0.1.0.3
- repline-0.1.6.0
- tasty-discover-3.0.2
- quickcheck-io-0.2.0
resolver: lts-9-3
